#include "editor.h"
#include "trs.h"
#include <GLFW/glfw3.h>

static const Binding bindings[] = {
    {Mode::ANY, GLFW_KEY_ESCAPE, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::NORMAL; }},
    {Mode::ANY, GLFW_KEY_T, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE; }},
    {Mode::ANY, GLFW_KEY_R, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE; }},
    {Mode::ANY, GLFW_KEY_S, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE; }},
    {Mode::ANY, GLFW_KEY_E, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR; }},

    {Mode::TRANSLATE, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_X; }},
    {Mode::TRANSLATE, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_Y; }},
    {Mode::TRANSLATE, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_Z; }},
    {Mode::TRANSLATE_X, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE; }},
    {Mode::TRANSLATE_X, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_Y; }},
    {Mode::TRANSLATE_X, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_Z; }},
    {Mode::TRANSLATE_Y, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_X; }},
    {Mode::TRANSLATE_Y, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE; }},
    {Mode::TRANSLATE_Y, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_Z; }},
    {Mode::TRANSLATE_Z, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_X; }},
    {Mode::TRANSLATE_Z, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE_Y; }},
    {Mode::TRANSLATE_Z, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::TRANSLATE; }},

    {Mode::ROTATE, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_X; }},
    {Mode::ROTATE, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_Y; }},
    {Mode::ROTATE, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_Z; }},
    {Mode::ROTATE_X, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE; }},
    {Mode::ROTATE_X, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_Y; }},
    {Mode::ROTATE_X, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_Z; }},
    {Mode::ROTATE_Y, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_X; }},
    {Mode::ROTATE_Y, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE; }},
    {Mode::ROTATE_Y, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_Z; }},
    {Mode::ROTATE_Z, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_X; }},
    {Mode::ROTATE_Z, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE_Y; }},
    {Mode::ROTATE_Z, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::ROTATE; }},

    {Mode::SCALE, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_X; }},
    {Mode::SCALE, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_Y; }},
    {Mode::SCALE, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_Z; }},
    {Mode::SCALE_X, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE; }},
    {Mode::SCALE_X, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_Y; }},
    {Mode::SCALE_X, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_Z; }},
    {Mode::SCALE_Y, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_X; }},
    {Mode::SCALE_Y, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE; }},
    {Mode::SCALE_Y, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_Z; }},
    {Mode::SCALE_Z, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_X; }},
    {Mode::SCALE_Z, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE_Y; }},
    {Mode::SCALE_Z, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SCALE; }},

    {Mode::TRANSLATE, GLFW_KEY_H, 0, false,
     [](EditorState &s, const Input &) { trs::translate(*s.selected, -s.cfg.keySensitivity, 0, 0); }},
    {Mode::TRANSLATE, GLFW_KEY_L, 0, false,
     [](EditorState &s, const Input &) { trs::translate(*s.selected, s.cfg.keySensitivity, 0, 0); }},
    {Mode::TRANSLATE, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::translate(*s.selected, 0, -s.cfg.keySensitivity, 0); }},
    {Mode::TRANSLATE, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::translate(*s.selected, 0, s.cfg.keySensitivity, 0); }},
    {Mode::TRANSLATE, GLFW_KEY_U, 0, false,
     [](EditorState &s, const Input &) { trs::translate(*s.selected, 0, 0, s.cfg.keySensitivity); }},
    {Mode::TRANSLATE, GLFW_KEY_D, 0, false,
     [](EditorState &s, const Input &) { trs::translate(*s.selected, 0, 0, -s.cfg.keySensitivity); }},

    {Mode::TRANSLATE_X, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::translate_local(*s.selected, -s.cfg.keySensitivity, 0, 0); }},
    {Mode::TRANSLATE_X, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::translate_local(*s.selected, s.cfg.keySensitivity, 0, 0); }},
    {Mode::TRANSLATE_Y, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::translate_local(*s.selected, 0, -s.cfg.keySensitivity, 0); }},
    {Mode::TRANSLATE_Y, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::translate_local(*s.selected, 0, s.cfg.keySensitivity, 0); }},
    {Mode::TRANSLATE_Z, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::translate_local(*s.selected, 0, 0, -s.cfg.keySensitivity); }},
    {Mode::TRANSLATE_Z, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::translate_local(*s.selected, 0, 0, s.cfg.keySensitivity); }},

    {Mode::ROTATE, GLFW_KEY_H, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_y(*s.selected, -s.cfg.keySensitivity); }},
    {Mode::ROTATE, GLFW_KEY_L, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_y(*s.selected, s.cfg.keySensitivity); }},
    {Mode::ROTATE, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_x(*s.selected, s.cfg.keySensitivity); }},
    {Mode::ROTATE, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_x(*s.selected, -s.cfg.keySensitivity); }},
    {Mode::ROTATE, GLFW_KEY_U, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_z(*s.selected, s.cfg.keySensitivity); }},
    {Mode::ROTATE, GLFW_KEY_D, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_z(*s.selected, -s.cfg.keySensitivity); }},

    {Mode::ROTATE_X, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_x_local(*s.selected, -s.cfg.keySensitivity); }},
    {Mode::ROTATE_X, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_x_local(*s.selected, s.cfg.keySensitivity); }},
    {Mode::ROTATE_Y, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_y_local(*s.selected, -s.cfg.keySensitivity); }},
    {Mode::ROTATE_Y, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_y_local(*s.selected, s.cfg.keySensitivity); }},
    {Mode::ROTATE_Z, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_z_local(*s.selected, -s.cfg.keySensitivity); }},
    {Mode::ROTATE_Z, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::rotate_z_local(*s.selected, s.cfg.keySensitivity); }},

    {Mode::SCALE, GLFW_KEY_H, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1.0f - s.cfg.keySensitivity, 1, 1); }},
    {Mode::SCALE, GLFW_KEY_L, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1.0f + s.cfg.keySensitivity, 1, 1); }},
    {Mode::SCALE, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1.0f - s.cfg.keySensitivity, 1); }},
    {Mode::SCALE, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1.0f + s.cfg.keySensitivity, 1); }},
    {Mode::SCALE, GLFW_KEY_U, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1, 1.0f + s.cfg.keySensitivity); }},
    {Mode::SCALE, GLFW_KEY_D, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1, 1.0f - s.cfg.keySensitivity); }},

    {Mode::SCALE_X, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1.0f - s.cfg.keySensitivity, 1, 1); }},
    {Mode::SCALE_X, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1.0f + s.cfg.keySensitivity, 1, 1); }},
    {Mode::SCALE_Y, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1.0f - s.cfg.keySensitivity, 1); }},
    {Mode::SCALE_Y, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1.0f + s.cfg.keySensitivity, 1); }},
    {Mode::SCALE_Z, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1, 1.0f - s.cfg.keySensitivity); }},
    {Mode::SCALE_Z, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::scale(*s.selected, 1, 1, 1.0f + s.cfg.keySensitivity); }},

    {Mode::SHEAR, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_X; }},
    {Mode::SHEAR, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_Y; }},
    {Mode::SHEAR, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_Z; }},
    {Mode::SHEAR_X, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR; }},
    {Mode::SHEAR_X, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_Y; }},
    {Mode::SHEAR_X, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_Z; }},
    {Mode::SHEAR_Y, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_X; }},
    {Mode::SHEAR_Y, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR; }},
    {Mode::SHEAR_Y, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_Z; }},
    {Mode::SHEAR_Z, GLFW_KEY_X, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_X; }},
    {Mode::SHEAR_Z, GLFW_KEY_Y, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR_Y; }},
    {Mode::SHEAR_Z, GLFW_KEY_Z, 0, true, [](EditorState &s, const Input &) { s.mode = Mode::SHEAR; }},

    // SHEAR_X: H/L = kxy, J/K = kxz
    {Mode::SHEAR_X, GLFW_KEY_H, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, -s.cfg.keySensitivity, 0, 0, 0, 0, 0); }},
    {Mode::SHEAR_X, GLFW_KEY_L, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, s.cfg.keySensitivity, 0, 0, 0, 0, 0); }},
    {Mode::SHEAR_X, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, -s.cfg.keySensitivity, 0, 0, 0, 0); }},
    {Mode::SHEAR_X, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, s.cfg.keySensitivity, 0, 0, 0, 0); }},

    // SHEAR_Y: H/L = kyx, J/K = kyz
    {Mode::SHEAR_Y, GLFW_KEY_H, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, -s.cfg.keySensitivity, 0, 0, 0); }},
    {Mode::SHEAR_Y, GLFW_KEY_L, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, s.cfg.keySensitivity, 0, 0, 0); }},
    {Mode::SHEAR_Y, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, 0, -s.cfg.keySensitivity, 0, 0); }},
    {Mode::SHEAR_Y, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, 0, s.cfg.keySensitivity, 0, 0); }},

    // SHEAR_Z: H/L = kzx, J/K = kzy
    {Mode::SHEAR_Z, GLFW_KEY_H, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, 0, 0, -s.cfg.keySensitivity, 0); }},
    {Mode::SHEAR_Z, GLFW_KEY_L, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, 0, 0, s.cfg.keySensitivity, 0); }},
    {Mode::SHEAR_Z, GLFW_KEY_J, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, 0, 0, 0, -s.cfg.keySensitivity); }},
    {Mode::SHEAR_Z, GLFW_KEY_K, 0, false,
     [](EditorState &s, const Input &) { trs::shear(*s.selected, 0, 0, 0, 0, 0, s.cfg.keySensitivity); }},

};

void editor::process_input(const Input &in, EditorState &state)
{
    Mode mode = state.mode;
    for (const Binding &b : bindings)
    {
        bool triggered = in.keys[b.key] == (b.oneShot ? KeyState::Released : KeyState::Down);
        if ((b.mode == mode || b.mode == Mode::ANY) && triggered && b.mods == in.mods)
        {
            b.action(state, in);
        }
    }
}
